### ISSUE TITLE
Error executing vim.schedule lua callback:

### ISSUE THREAD

**Issue by greensegfault** [mrcjkb/rustaceanvim#449] opened 2024-07-10 05:35 UTC
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Debian 12

### Output of :checkhealth rustaceanvim

```console
3 rustaceanvim: require("rustaceanvim.health").check()
   4
   5 Checking for Lua dependencies
   6 - OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.
   7
   8 Checking external dependencies
   9 - OK rust-analyzer: found rust-analyzer 0.3.2029-standalone
  10 - OK Cargo: found cargo 1.79.0 (ffa9cf99a 2024-06-03)
  11 - OK rustc: found rustc 1.79.0 (129f3b996 2024-06-10)
  12 - OK debug adapter: found codelldb
  13
  14 Checking config
  15 - OK No errors found in config.
  16
  17 Checking for conflicting plugins
  18 - OK No conflicting plugins detected.
```

### How to reproduce the issue

```console
Open src/main.rs and start editing.
```

### Expected behaviour

No error upon editing

### Actual behaviour

```
With latest rust-analyzer, nvim, Mason, I get the following error:

Error executing vim.schedule lua callback: ...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/
dap.lua:46: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/dap.lua:46: in function 'get_cargo_
args_from_runnables_args'
        ...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/dap.lua:276: in function 'start'
        ...y/rustaceanvim/lua/rustaceanvim/commands/debuggables.lua:125: in function 'callback'

        ...y/rustaceanvim/lua/rustaceanvim/commands/debuggables.lua:160: in function 'handler'
        .../apps/nvim/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### The minimal config used to reproduce this issue.

```Lua
This is my config:
 {
    'mrcjkb/rustaceanvim',
    version = '^4', -- Recommended
    lazy = false, -- This plugin is already lazy
  },
```

**Comment by mrcjkb** [comment] 2024-07-10 07:03
Duplicate of #446

**Closed by mrcjkb** 2024-07-10 07:03 UTC
Labels: bug
