### ISSUE TITLE
Nix-based minimal rustaceanvim doesn't work under macOS 15.1.1

### ISSUE THREAD

**Issue by mistzzt** [mrcjkb/rustaceanvim#586] opened 2024-11-21 04:44 UTC
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).
- [X] This is an issue about rustaceanvim, not rust-analyzer or Neovim.
- [X] This is [not an issue with autocompletion](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#im-having-issues-with-autocompletion).

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

macOS 15.1.1

### Output of :checkhealth rustaceanvim

```console
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- WARNING dap not installed. Needed for debugging features [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap)

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 2024-09-02
- OK Cargo: found cargo 1.82.0 (8f40fc59f 2024-08-21)
- OK rustc: found rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball)
- OK lldb: found lldb version 16.0.6

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
- OK .vscode/settings.json loaded without errors.
```

### How to reproduce the issue

```console
nix run "github:mrcjkb/rustaceanvim#nvim-minimal-stable"
:e src/eval/main.rs
// `main.rs` is defined as one of the executables in a cargo-based project


# from Cargo.toml
[[bin]]
name = "eval"
path = "src/eval/main.rs"


Interestingly, I created an empty project with `cargo new foo` and found rustaceanvim worked with the minimal project.
```

### Expected behaviour

I expect to see static analysis result from rust-analyzer. For example, I have the following lines in my code:
```rust
let foo: () = 42;
```

and I expect rust-analyzer to catch the type error and show the following message:
```rust
mismatched types
expected `()`, found integer
```

Additionally, I expect to see `eval` as one of the runnables from `:RustLsp runnables`.

### Actual behaviour

On NixOS 24.05 and Ubuntu 22.04, given the minimal config and same Cargo project, I _was able to_ successfully run neovim with the minimal rustaceanvim config and observe the desired behavior from rustaceanvim. However, on macOS 14.1.1 with Nix 2.18.1, I _can't_ find any error reported from rust-analyzer and rustaceanvim.

1. I could confirm `rust-analyzer` is running by `ps aux | grep rust-analyzer`.
2. Rust-analyzer's log is created (confirmed by checking `:RustLsp logFile`) but it is empty.

Additionally, I followed rust-analyzer's troubleshooting guide. First, I set `RA_LOG=info` and found no obvious error in the log file. I've attached the log file [rust-analyzer.log](https://github.com/user-attachments/files/17839928/rust-analyzer.log) to the thread and include the last few lines here:
```log
...
2024-11-21T04:29:09.021719Z  INFO /Users/zwang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-impl-1.0.65: BuildScriptOutput { cfgs: [], envs: Env { entries: {} }, out_dir: None, proc_macro_dylib_path: Some(AbsPathBuf("/Users/zwang/research/ink/target/debug/deps/libthiserror_impl-b647c2f6905f99a6.dylib")) }
2024-11-21T04:29:09.021722Z  INFO /Users/zwang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-1.0.65: BuildScriptOutput { cfgs: [], envs: Env { entries: {"OUT_DIR": "/Users/zwang/research/ink/target/debug/build/thiserror-af9f6290ae80905b/out"} }, out_dir: Some(AbsPathBuf("/Users/zwang/research/ink/target/debug/build/thiserror-af9f6290ae80905b/out")), proc_macro_dylib_path: None }
2024-11-21T04:29:09.021725Z  INFO /Users/zwang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-attributes-0.1.27: BuildScriptOutput { cfgs: [], envs: Env { entries: {} }, out_dir: None, proc_macro_dylib_path: Some(AbsPathBuf("/Users/zwang/research/ink/target/debug/deps/libtracing_attributes-39a9abc361a1ebbf.dylib")) }
2024-11-21T04:29:09.021728Z  INFO /Users/zwang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zerocopy-derive-0.7.35: BuildScriptOutput { cfgs: [], envs: Env { entries: {} }, out_dir: None, proc_macro_dylib_path: Some(AbsPathBuf("/Users/zwang/research/ink/target/debug/deps/libzerocopy_derive-29f37364c1748c76.dylib")) }
2024-11-21T04:29:09.928586Z  WARN notify error: 
No path was found. about ["/Users/zwang/research/ink/rust-analyzer.toml"]
```

I also tried an alternative debug option `RA_LOG=project_model=debug` and again found no obvious error either. I've also attached the [corresponding log](https://github.com/user-attachments/files/17839958/rust-analyzer-2.log) for completeness.

Finally, I ran `rust-analyzer analysis-stats .` in a neovim terminal for the same project:
```
$ echo $PATH
/nix/store/a1b8c8sibfbi28nn2dfz0y06ixca3arp-rust-analyzer-2024-09-02/bin /nix/store/arsxsvbjmappgjrxviayspqnjm1nhrma-cargo-1.82.0/bin /nix/store/5nz0x
9bfbz8bqj25gxbhc7p8mgyy463g-rustc-wrapper-1.82.0/bin /nix/store/3cb15x50v9g8hg2yaxdzqcyhmlrn9h6f-lldb-16.0.6/bin /opt/homebrew/bin /opt/homebrew/sbin 
/Users/zwang/.nix-profile/bin /etc/profiles/per-user/zwang/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/bin /u
sr/sbin /bin /sbin /nix/store/29lhfiwwm4fx8pbcmqxzfhrys2my82dj-neovim-ruby-env/bin
$ rust-analyzer analysis-stats .
Database loaded:     3.89s, 0b (metadata 649.90ms, 0b; build 991.83ms, 0b)
  item trees: 85
Item Tree Collection: 50.23ms, 0b
  crates: 4, mods: 36, decls: 599, bodies: 566, adts: 39, consts: 34
Item Collection:     6.35s, 0b
Body lowering:       583.11ms, 0b                                             
  exprs: 44105, ??ty: 8 (0%), ?ty: 4 (0%), !ty: 1                             
  pats: 6774, ??ty: 3 (0%), ?ty: 1 (0%), !ty: 0
Inference:           2.24s, 0b
MIR lowering:        127.00ms, 0b
Mir failed bodies: 2 (0%)
Data layouts:        1.27ms, 0b
Failed data layouts: 0 (0%)
Const evaluation:    33.95ms, 0b
Failed const evals: 0 (0%)
Total:               9.38s, 0b
```

Right now, I have no clue what to try/diagnose next. I appreciate any idea/help you can provide. Thank you.

### The minimal config used to reproduce this issue.

I tried both `nix run "github:mrcjkb/rustaceanvim#nvim-minimal-stable"` and `nix run "github:mrcjkb/rustaceanvim#nvim-minimal-nightly"`.

Additionally, I tried the following rust-analyzers versions:
1. latest nightly rust-analyzer from [nix-community/fenix](https://github.com/nix-community/fenix)
2. rust-analyzer from nixpkgs 24.05 and unstable.
3. rust-analyzer defined in rustaceanvim's flake.nix

Finally, I tested the rust-analyzer settings from `neovim/nvim-lspconfig` and confirmed the local rust-analyzer works.

**Comment by mrcjkb** [comment] 2024-11-21 07:03
oof, this is going to be hard for me to troubleshoot without a mac 😅.

In the logs, it looks like rust-analyzer is using clippy for diagnostics. rustaceanvim defaults to enabling clippy if it finds it on the `PATH`. So I'd suggest you try disabling that. 
If that solves the problem for you, then it's likely an issue with clippy.

**Comment by mrcjkb** [comment] 2024-11-22 07:59
> I thought this was fixed in neovim but didn't seem so.

I believe it has been fixed in Neovim nightly.

**Comment by mrcjkb** [comment] 2024-11-29 16:19
@antoineco this section of your diff

```diff
>   settings = {
>     ["rust-analyzer"] = {
>       check = <table 1>,
>       checkOnSave = true,
>       files = <table 2>
>     }
>   },
```

tells me rustaceanvim is likely detecting a clippy install and configuring rust-analyzer to use it for checks.
See [my previous comment](https://github.com/mrcjkb/rustaceanvim/issues/586#issuecomment-2490225793) and `:h rustaceanvim.config` for how to disable clippy.

**Comment by antoineco** [comment] 2024-11-29 16:25
I will try that, but @mistzzt confirmed that it didn't work for them. I can also run rust-analyzer successfully with clippy support outside of rustaceannvim

**Comment by mrcjkb** [comment] 2024-11-29 17:14
> but @mistzzt confirmed that 

they haven't confirmed yet that it isn't being picked up (see [my other comment](https://github.com/mrcjkb/rustaceanvim/issues/586#issuecomment-2504772842)).

Another thing you could try is explicitly setting the command to run rust-analyzer. In your lspconfig settings, it's using a path from the nix store.

Also, please ensure you are using a minimal config without any other plugins that could be interfering.

**Comment by antoineco** [comment] 2024-11-29 21:10
I confirm that the issue occurs with:
- [minimal.lua](https://github.com/mrcjkb/rustaceanvim/blob/v5.15.3/troubleshooting/minimal.lua)
- The following rustaceannvim options:
  ```lua
   vim.g.rustaceanvim {
     tools.enable_clippy = false,
     server.cmd = { "/nix/store/kilidiy72famzqx6anbsvgp1qgp9yz8x-rust-default-1.83.0/bin/rust-analyzer", "--log-file", "/Users/acotten/ra.log" }
   }
   ```

Here is the a log line from rust-analyzer ran with `RA_LOG=info`:

```
2024-11-29T20:54:52.975282Z  INFO Running build scripts: cd "/Users/acotten/myproject" && RA_RUSTC_WRAPPER="1" RUSTC_WRAPPER="/nix/store/kilidiy72famzqx6anbsvgp1qgp9yz8x-rust-default-1.83.0/bin/rust-analyzer" RUSTUP_TOOLCHAIN="/nix/store/kilidiy72famzqx6anbsvgp1qgp9yz8x-rust-default-1.83.0" "/nix/store/kilidiy72famzqx6anbsvgp1qgp9yz8x-rust-default-1.83.0/bin/cargo" "check" "--quiet" "--workspace" "--message-format=json" "--manifest-path" "/Users/acotten/myproject/Cargo.toml" "--all-targets" "--keep-going"
```
(I verified that the word "clippy" wasn't appearing anywhere in the logs)

**Comment by mrcjkb** [comment] 2024-11-29 21:24
Another thing I noticed (but forgot to mention in my previous comment):
Your rustaceanvim client config appears to be missing the `workspace_folders` field.
rustaceanvim uses `cargo metadata` to try and find the workspace root.
And if that doesn't yield anything, it falls back to looking for a `Cargo.toml` or a `rust-project.json`.

The `standalone = true` option also indicates that it's not recognising your project as a rust project and is running in standalone mode (which has reduced functionality).

You can debug that by calling `require("rustaceanvim.cargo").get_root_dir(file_name)`.

**Comment by antoineco** [comment] 2024-11-29 21:40
Here is the output of `cargo metadata --format-version=1` for information:

```json
{"packages":[{"name":"myproject","version":"0.0.0","id":"path+file:///Users/acotten/myproject#0.0.0","license":null,"license_file":null,"description":null,"source":null,"dependencies":[],"targets":[{"kind":["lib"],"crate_types":["lib"],"name":"myproject","src_path":"/Users/acotten/myproject/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},{"kind":["bin"],"crate_types":["bin"],"name":"myproject","src_path":"/Users/acotten/myproject/src/main.rs","edition":"2021","doc":true,"doctest":false,"test":true}],"features":{},"manifest_path":"/Users/acotten/myproject/Cargo.toml","metadata":null,"publish":[],"authors":[],"categories":[],"keywords":[],"readme":null,"repository":null,"homepage":null,"documentation":null,"edition":"2021","links":null,"default_run":null,"rust_version":null}],"workspace_members":["path+file:///Users/acotten/myproject#0.0.0"],"workspace_default_members":["path+file:///Users/acotten/myproject#0.0.0"],"resolve":{"nodes":[{"id":"path+file:///Users/acotten/myproject#0.0.0","dependencies":[],"deps":[],"features":[]}],"root":"path+file:///Users/acotten/myproject#0.0.0"},"target_directory":"/Users/acotten/myproject/target","version":1,"workspace_root":"/Users/acotten/myproject","metadata":null}
```

Besides the `src` directory, the project contains only this minimal `Cargo.toml`:

```toml
[package]
name = "myproject"
edition = "2021"
publish = false
```

The command `:=require("rustaceanvim.cargo").get_root_dir("main.rs")` prints:

```
/Users/acotten/myproject
```

**Comment by antoineco** [comment] 2024-11-29 22:23
The nil `workspace_folders` doesn't seem to be the issue but I think we are getting close.

Remember when I said things started working after I copied all sources (and Cargo.toml) to a sub-directory?
I compared the output of `:=vim.lsp.get_clients()[1].config` in both scenarios, and to my surprise they were identical, with the exception of `root_dir` which was now the sub-directory. Yet:
- When sources are in the root directory, the language server keeps being disfunctional consistently.
- When sources and Cargo.toml are copied (not moved) to the sub-directory, the language server works consistently.

I would immediately assume this is an issue with rust-analyzer, but the fact that it works consistently with nvim-lspconfig's defaults makes me extremely confused.

**Comment by mrcjkb** [comment] 2024-11-29 22:45
Yep, I just reproduced your project structure and am seeing this diagnostic (it shows up after an edit):

![](https://github.com/user-attachments/assets/537ff97e-a256-4993-9f8c-9ffab75759e5)

```
This file is not included in any crates, so rust-analyzer can't offer IDE services.

If you're intentionally working on unowned files, you can silence this warning by adding "unlinked-file" to rust-analyzer.diagnostics.disabled in your settings.
```

No idea why it's working with nvim-lspconfig though. Perhaps it spawns a separate client in standalone mode?

**Comment by antoineco** [comment] 2024-11-29 22:48
Interestingly I've never seen this message.

Here is a trivial project with which the issue occurs: https://github.com/antoineco/adventofcode2024

**Comment by mrcjkb** [comment] 2024-11-29 23:06
Just cloned that project and it works fine on my end :man_shrugging: 

But hover and completion, etc. not working indicates that it may be running in standalone mode for some reason.

**Comment by antoineco** [comment] 2024-11-29 23:11
In the case where I copy the sources to a sub-directory and things start working, the client config shows `standalone = true` too.

The fact that the location of the files matter and that it occurs only with rustaceannvim seems absurd to me. I think I have exhausted all my ideas for now, but I'll share a screen recording eventually to demonstrate what is going on.

**Comment by mrcjkb** [comment] 2024-11-29 23:38
> The fact that the location of the files matter and that it occurs only with rustaceannvim seems absurd to me

if you're referring to a rust file in the project root, then you're probably running into what the diagnostic I posted is saying.
I don't know why you're not getting that diagnostic, but the reduced functionality is a symptom of rust-analyzer running in detached mode.

**Comment by antoineco** [comment] 2024-11-29 23:54
No no, I never drop Rust files into the project root, always under `src/`.

I was referring to the fact that rust-analyzer starts working when the directory tree changes from:

```
.
├── .envrc
├── Cargo.toml
└── src
    ├── lib.rs
    └─── main.rs
```

```
.
├── .envrc
└── foo
    ├── Cargo.toml
    └── src
        ├── lib.rs
        └── main.rs
```

Every time I run into the problem, this simple relocation makes the language server work with rustaceannvim and I can't make any sense of it. I'd be curious to know whether @mistzzt observes that too.

**Comment by mrcjkb** [comment] 2024-11-30 08:12
That's very curious indeed. Do you have anything else in the root directory?

**Comment by antoineco** [comment] 2024-11-30 08:44
Yes I remain in the devShell after moving to the sub-directory. I do not have any Rust toolchain in my PATH outside of devShells.

```
$ rustc --version
zsh: command not found: rustc
```
```
$ rust-analyzer --version
zsh: command not found: rust-analyzer
```
```console
$ nix develop 'github:antoineco/dotfiles#rust' -c zsh
```
```
$ rustc --version
rustc 1.83.0 (90b35a623 2024-11-26)
```
```
$ rust-analyzer --version
rust-analyzer 1.83.0 (90b35a62 2024-11-26)
```
```console
$ mkdir myproject && cd myproject
```
```console
$ cargo init
    Creating binary (application) package
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
```
```console
$ nix run 'github:mrcjkb/rustaceanvim#nvim-minimal-stable' -- src/main.rs
(opens  NVIM v0.10.2)
```

In this state, clippy diagnostics are being shown, but no completion, jump or hover works:
<img width="764" alt="image" src="https://github.com/user-attachments/assets/05d2af18-9c0e-46b5-9d51-a51bb01ef3ba">

Also, `rust-analyzer` processes aren't terminated after exiting Neovim:
```console
$ ps -ax | grep rust
28550 ??         2:20.25 /nix/store/xnvvdwlwfil5rr3krd9rx0559zw5x58c-rust-analyzer-unwrapped-2024-11-11/bin/rust-analyzer --log-file /tmp/nvim-rustaceanvim.acotten/AYA66d/0-rust-analyzer.log
28848 ??         1:45.46 /nix/store/xnvvdwlwfil5rr3krd9rx0559zw5x58c-rust-analyzer-unwrapped-2024-11-11/bin/rust-analyzer --log-file /tmp/nvim-rustaceanvim.acotten/MAZ0Vz/0-rust-analyzer.log
29319 ??         0:38.61 /nix/store/xnvvdwlwfil5rr3krd9rx0559zw5x58c-rust-analyzer-unwrapped-2024-11-11/bin/rust-analyzer --log-file /tmp/nix-shell.frhxQg/nvim-rustaceanvim.acotten/vf9vTP/0-rust-analyzer.log
29740 ??         0:14.73 /nix/store/xnvvdwlwfil5rr3krd9rx0559zw5x58c-rust-analyzer-unwrapped-2024-11-11/bin/rust-analyzer --log-file /tmp/nix-shell.vJuJbV/nvim-rustaceanvim.acotten/76QoF4/0-rust-analyzer.log
```

Now comes the fun part:

```console
$ mkdir foo && mv Cargo.toml src foo && cd foo
(I am now in the myproject/foo directory)
```
```console
$ nix run 'github:mrcjkb/rustaceanvim#nvim-minimal-stable' -- src/main.rs
(opens  NVIM v0.10.2)
```

LSP features work consistently (in this case, omnicompletion with `C-X C-O`):
<img width="769" alt="image" src="https://github.com/user-attachments/assets/3615428b-1421-4ed5-b8ce-3f9d3c59a7d4">

**Comment by antoineco** [comment] 2024-11-30 09:04
I think I get it now. The `.direnv/` directory is not present in these two cases:
- Right after creating the project and using `nix develop`
- After moving Rust files to a sub-directory of the project

It is however causing issues when `Cargo.toml` is on the same level as `.direnv/`.

Uuuufff.

The only mystery left to be solved is why the `.direnv/` directory doesn't trip `rust-analyzer` outside of rustaceannvim.

**Comment by antoineco** [comment] 2024-11-30 09:15
Relevant comment in the rust-analyzer issues:

- https://github.com/rust-lang/rust-analyzer/issues/14734#issuecomment-2476773659

**Comment by mrcjkb** [comment] 2024-11-30 09:35
hmm, the fact that it works in nvim-lspconfig is possibly because rustaceanvim [registers capabilities that lspconfig doesn't](https://github.com/mrcjkb/rustaceanvim/blob/4ac7a3c6cca9e393229651cc90733afbdc7c6395/lua/rustaceanvim/config/server.lua#L77).

**Comment by mistzzt** [comment] 2024-11-30 20:08
Hi all, sorry for my recent absence. Similar to what @antoineco observed (thank you so much for investigating this!), I realized that my project contained a top-level `.direnv` directory generated by nix-direnv -- after disabling nix-direnv and removing the `.direnv` directory, I found that rustaceanvim worked perfectly on my setup. I plan to look into this further next week once I have more time.

**Comment by antoineco** [comment] 2024-11-30 21:00
@mistzzt it is indeed a problem with rust-analyzer; rustaceanvim only make the problem more visible somehow.

You can see above that I pushed a commit to my dotfiles, claiming in the commit message that excluding the `.direnv` directory in rust-analyzer did not work, based on a conversation I found in the rust-analyzer issue tracker. It turns out that configuring rust-analyzer that way works perfectly fine on my end, so maybe give it a try and report. 🙂

**Closed** 2024-12-01 03:41 UTC
Labels: bug
