### ISSUE TITLE
Loading error when opening large files

### ISSUE THREAD

**Issue by 0xAndoroid** [mrcjkb/rustaceanvim#295] opened 2024-03-16 15:17 UTC
### Neovim version (nvim -v)

v0.10.0-dev-2601+gb7779c514-Homebrew

### Operating system/version

macOS 14.2.1

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.76.0 (07dca489 2024-02-04)
- OK Cargo: found cargo 1.76.0 (c84b36747 2024-01-18)
- OK rustc: found rustc 1.76.0 (07dca489a 2024-02-04)
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
1. Install rustaceanvim
2. Open large file (>2000 lines) right after launching nvim
```

### Expected behaviour

No errors should appear

### Actual behaviour

<img width="723" alt="Screenshot 2024-03-16 at 11 14 36" src="https://github.com/mrcjkb/rustaceanvim/assets/42178850/9ab7206d-027b-4ed2-8af2-72dfc11057d6">

### The minimal config used to reproduce this issue.

```Lua
https://github.com/AstroNvim/astrocommunity/blob/dd78f631dae0d444b3cef6f657b0d00c166ba8e5/lua/astrocommunity/pack/rust/init.lua#L66
```

**Comment by mrcjkb** [comment] 2024-03-17 08:49
Hey 👋 

Thanks for reporting. This is a duplicate of https://github.com/mrcjkb/rustaceanvim/discussions/219.

But I'll leave this open and see if I can make it fail silently.

**Closed** 2024-03-17 13:24 UTC
Labels: bug
