### ISSUE TITLE
improving :RustLsp renderDiagnostic

### ISSUE THREAD

**Issue by rywng** [mrcjkb/rustaceanvim#603] opened 2024-12-04 02:57 UTC
### Feature description

Hello, I have two issues with the command:

1. In current implementation, running it again without arguments (`:RustLsp renderDiagnostic`) only cycles **forward** but not backwards, which is not really convenient and the functionality can be replaced by either nvim's built ins like `vim.diagnostic.goto_next()` and `vim.diagnostic.goto_prev()` or 3rd party plugins like `:Telescope diagnostics`. This is also talked about in #599 
2. If you run `:RustLsp renderDiagnostic current`, it shows up the diagnostic window with a option to "open in split", but running the command again wont focus on the window, and afaik there's now way to actually access the "open in split" menu:
![image](https://github.com/user-attachments/assets/e6522a86-9782-4968-977c-4a63148f1a43)

For reference, in nvim's built in lsp commands, for example if you press K on a symbol, on the first time it would open up a popup:
![image](https://github.com/user-attachments/assets/8986e5e9-bd20-47ff-b760-1dcab67eca84)

and the second time you press it will focus the pop up and allow you to navigate inside the menu:

![image](https://github.com/user-attachments/assets/8de364e5-dc63-4876-bb67-c5ff92ac60d1)

So I would suggest removing the `cycle` option, and enable users to focus the pop up menu when running the command twice, like many other lsp commands.

**Comment by mrcjkb** [comment] 2024-12-04 07:28
Hey :wave:

As you mentioned, your first issue is a duplicate of #599, so let's remove that from this issue and adjust the title.

Regarding your second issue:

The `renderDiagnostic` command uses `vim.lsp.util.open_floating_preview`, which is different from Neovim's hover windows (which is what you are referring to with "pressing `K` on a symbol").
You can use `<C-w>w` (ctrl+w+w) and Neovim's various other window navigation keymaps, (`<C-w>h`, `<C-w>j`, etc.) to navigate to the hover window.
Given the difference and the fact that you can navigate to the diagnostic window, I don't think implementing an equivalent to "pressing K twice" is really worth the added code complexity (but I'm open to being proven wrong via a PR :smile:).

That being said, it's probably worth adding a `<Plug>` mapping, like the one for the `hover action` command.

I'll close this for now. Please feel free to open a PR if you would like the `K+K`-like behaviour, e.g. by running the command a second time, without any arguments.

**Closed by mrcjkb** 2024-12-04 07:28 UTC
Labels: enhancement
