### ISSUE TITLE
Bad Interaction with neoconf: Rustaceanvim ignores `.vscode/settings.json` lsp settings loaded by neoconf

### ISSUE THREAD

**Issue by futile** [mrcjkb/rustaceanvim#475] opened 2024-08-06 15:49 UTC
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [ ] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

NixOS 24.11 (unstable)

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- WARNING dap not installed. Needed for debugging features [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap)

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.81.0-nightly (fcc325f 2024-07-17)
- OK Cargo: found cargo 1.81.0-nightly (a2b58c3da 2024-07-16)
- OK rustc: found rustc 1.81.0-nightly (fcc325f1b 2024-07-17)

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
1. Use a config with both `rustaceanvim` and `neoconf`
2. Add a `.vscode/settings.json` to a project, check that it is loaded by neoconf using `:Neoconf show` and/or `:Neoconf lsp`
3. `rustaceanvim` will not pick up the settings shown by `neoconf`
```

### Expected behaviour

`rustaceanvim` should ideally also pick up the settings loaded from the `.vscode/settings.json` file by `neoconf`.

Alternatively: A snippet in the Readme on how to set this up? I couldn't figure it out at least, although https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#how-to-dynamically-load-different-rust-analyzer-settings-per-project looked like it goes in this direction, but it wasn't enough for me.

Sorry for not including more detailed steps, I thought it's probably the case that neoconf tries to configure `lspconfig` somehow, which `rustaceanvim` overrides.

### Actual behaviour

`rustaceanvim` **does not** pick up the settings loaded from the `.vscode/settings.json` file by `neoconf`.

### The minimal config used to reproduce this issue.

```Lua
vim.env.LAZY_STDPATH = '.repro'
load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()

require('lazy.minit').repro {
  spec = {
    {
      'mrcjkb/rustaceanvim',
      version = '^5',
      init = function()
        -- Configure rustaceanvim here
        vim.g.rustaceanvim = {}
      end,
      lazy = false,
    },
    {
      "folke/neoconf.nvim",
    },
  },
}
```

**Comment by mrcjkb** [comment] 2024-08-06 15:57
Duplicate of

  - https://github.com/mrcjkb/rustaceanvim/issues/53

Neoconf support is not planned.
rustaceanvim has experimental support for loading `.vscode/settings.json` settings (disabled by default, can be enabled with `vim.g.rustaceanvim.server.load_vscode_settings`, see `:h rustaceanvim.config`).

It's been around for a while, so maybe it's time to make it non-experimental.

**Closed** 2024-08-06 15:57 UTC
Labels: duplicate

**Comment by futile** [comment] 2024-08-06 16:02
Ohh thanks, missed that option and issue, thanks a lot for the quick reply!

**Comment by mrcjkb** [comment] 2024-08-06 16:02
> It's been around for a while, so maybe it's time to make it non-experimental.

https://github.com/mrcjkb/rustaceanvim/releases/tag/5.2.0

**Comment by futile** [comment] 2024-08-06 16:17
It's working, thanks so much! :) Only issue seems to be that variables, e.g., `${workspaceFolder}`, are not expanded. Not super horrible, I can just adjust them, but wanted to let you know.

Thanks again! :)

**Comment by mrcjkb** [comment] 2024-08-06 16:31
> Only issue seems to be that variables, e.g., ${workspaceFolder}, are not expanded.

Yep, the support is very rudimental :smile:
