### ISSUE TITLE
[Windows] Cannot run in nushell

### ISSUE THREAD

**Issue by shouyierban** [mrcjkb/rustaceanvim#561] opened 2024-11-05 10:29 UTC
**Thank you for you job, it is a very usefull plugins.**

Long story shart, I were using wezterm with nushell in windows systerm. when I run codes with hover actions, the terminal always fails to execute commands. It seems that the correct path cannot be opened. Normally, nushell does not need to `""` when execute `cd` commands.

![Quicker1](https://github.com/user-attachments/assets/ce1a5910-63d8-4aa7-b659-2fbc36645e1b)

**Comment by mrcjkb** [comment] 2024-11-05 15:45
Hey :wave: 

I can't reproduce this on Linux, so it appears to be a Windows only issue.
You often don't need to quote paths, even with other shells, but it makes it easier to handle paths containing spaces.

Are you able to run the command in nushell on Windows?
By the looks of it, nushell is removing `\t` and `\b` (which it may be interpreting as whitespace, e.g. `\t = TAB`?).
If you cannot run the command in nushell on Windows, I would say this is likely a nushell bug.

**Comment by shouyierban** [comment] 2024-11-06 05:29
> Hey 👋
> 
> I can't reproduce this on Linux, so it appears to be a Windows only issue. You often don't need to quote paths, even with other shells, but it makes it easier to handle paths containing spaces.
> 
> Are you able to run the command in nushell on Windows? By the looks of it, nushell is removing `\t` and `\b` (which it may be interpreting as whitespace, e.g. `\t = TAB`?). If you cannot run the command in nushell on Windows, I would say this is likely a nushell bug.

Thanks for reply.
If I execute the following command in nushell, can work very well.
` cd E:\tmp\bba | cargo run --package bba --bin bba --all-features `

This is no problem, even if I run the file in the current folder.
`cargo run main.rs`

The above problem only occurs when I use hover actions, it automatically `cd` the path and adds `“”`. Is there any way to make it pass the path without adding the` ''”`?

**Comment by mrcjkb** [comment] 2024-11-06 06:06
> If I execute the following command in nushell, can work very well.
`cd E:\tmp\bba | cargo run --package bba --bin bba --all-features`

That is not what I asked, sorry. Let me clarify:
I asked if you can run `cd "E:\tmp\bba"` (with quotes) in nushell on Windows. If not, it's possibly a nushell on Windows bug, because that is possible on UNIX systems.

**Comment by mrcjkb** [comment] 2024-11-06 07:49
See also [this comment](https://github.com/nushell/nushell/issues/14010#issuecomment-2395501257):

> Strings with spaces have to be quoted: print "hello, world".

To be able to handle paths with spaces, they must be quoted. This is the case for nushell too.
Closing, as this is a bug in nushell on Windows. There's nothing I can do here. Please open an issue in the nushell repository, if none exists.

**Closed by mrcjkb** 2024-11-06 07:49 UTC
Labels: upstream

**Comment by shouyierban** [comment] 2024-11-08 15:31
Hi @mrcjkb , I found the cause of the problem finally. When nushell executes the command, the backslash in double quotes is treated as an escape character. So just replace the double quotes with single quotes or delete to solve the problem when create  `cd` command for the path.
please find the source code in line 47 of `./lua/rustaceanvim/shell.lua`,
change `return ('cd "%s" '):format(path)` to `return ('cd %s'):format(path)` or `return ("cd '%s' "):format(path)`

**Comment by mrcjkb** [comment] 2024-11-09 17:09
I've implemented a fix. But again, this is a bug in Nushell on Windows and should be reported there.

**Comment by mikavilpas** [comment] 2024-11-09 19:42
I have been thinking this could be a neovim bug, specific to nushell and windows. I had a long discussion about something similar in a bug report in yazi.nvim here https://github.com/mikavilpas/yazi.nvim/issues/366

If anyone finds some information about this (maybe a fix), I would appreciate a message, for example in this thread.

Wishing everyone a nice weekend 🙂

**Comment by shouyierban** [comment] 2024-11-10 02:38
@mrcjkb It works very well after updating. Thanks  for  your job, and thanks for @mikavilpas suggestions.
